- name: Run script
        run: |
          python sakurazaka-rss.py
          python Nogizaka-rss/nogizaka-rss.py  # 💡 フォルダを指定して実行
      
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # 💡 保存するファイル名にフォルダ名を忘れずに追加！
          git add feed.xml Nogizaka-rss/nogizaka.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feeds" && git push)